### ISSUE TITLE
Crash while importing FBX

### ISSUE THREAD

**Issue by thepenguinmaster** [SiliconStudio/xenko#142]
THe application crashed after importing materials, texures, model and entity from an FBX file. The mesh was a simple subdivided and smoothed sphere with a UV texture applied and mapped. The normals are facing inwards.

Paradox Version: 1.0.0-beta06
GameStudio Version: 4
Error Message: Unexpected exception
User: Administrator
Current Directory: C:\Program Files (x86)\Paradox\GamePackages\Paradox.1.0.0-beta06\Bin\Windows-Direct3D11
OS Version: Microsoft Windows NT 6.2.9200.0
Command Line Args: 
Exception type: NullReferenceException
Exception message: Object reference not set to an instance of an object.
StackTrace:    at SiliconStudio.Paradox.Engine.MeshProcessor.Draw(GameTime time)
   at SiliconStudio.Paradox.EntityModel.EntitySystem.Draw(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameSystemCollection.Draw(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.Draw(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.DrawFrame()
   at SiliconStudio.Paradox.Games.GameBase.Tick()
   at SiliconStudio.Paradox.Games.GamePlatform.Tick()
   at SiliconStudio.Paradox.Games.GamePlatform.OnRunCallback()
   at SiliconStudio.Paradox.Games.GameWindowDesktop.<>c__DisplayClass2.<Run>b__0()
   at SiliconStudio.Paradox.Games.WindowsMessageLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at SiliconStudio.Paradox.Games.GameWindowDesktop.Run()
   at SiliconStudio.Paradox.Games.GamePlatform.Run(GameContext gameContext)
   at SiliconStudio.Paradox.Games.GameBase.Run(GameContext gameContext)
   at SiliconStudio.Paradox.GameStudio.ParadoxViewService.ParadoxUIThread(Object projectSession)
   at SiliconStudio.Core.Diagnostics.SafeAction.<>c__DisplayClass4.<Wrap>b__3(Object obj)

**Comment by thepenguinmaster** [comment]
Yes, I will see if I can find the problem file. I think I ended up recreating the file completely, moving it to another folder along with the textures, and it seemed to work. I whoudl be able to recreate the problem. I will recreate the problem and send you the fbx file.

**Comment by thepenguinmaster** [comment]
I have sent the files, can you verify that you have recieved them?

**Comment by xen2** [comment]
Where did you send it? Didn't see anything in our mailbox.

**Comment by thepenguinmaster** [comment]
Looks like the email server kicked it back. I tried to zip (Rar) and send the whole project. Is there somewhere I can uplaod the project?
Date: Tue, 6 Jan 2015 18:04:34 -0800

**Comment by xen2** [comment]
Not sure if you tried .zip or .rar, but if you only tried .rar, .zip usually works better.

**Comment by xen2** [comment]
Closing for now due to lack of repro, please reopen if you still have problems with latest version and send us repro files. Thanks!
