### ISSUE TITLE
Versions 1.1.4 & 1.2.0 don't let me create session

### ISSUE THREAD

**Issue by SimonLeeroy** [SiliconStudio/xenko#256]
As I mentioned, versions 1.1.4 & 1.2.0 don't let me create a New Game, although New Package can be created without any problems. Working with version 1.0 is free from errors.
My PC has Visual Studio 2013 Ultimate and Windows 8.1 Pro installed. 
Furthermore you can see the specifications of the notebook and two screenshots showing my selections and the error messages.  What can cause that?
http://www.notebookcheck.net/Review-Acer-Aspire-V5-573G-54208G50aii-Notebook.99264.0.html
I also tried running both graphics cards, but without success. 

![pic1](https://cloud.githubusercontent.com/assets/13474364/8862297/d62c0dca-318f-11e5-96f9-026f411fa616.png)
![pic2](https://cloud.githubusercontent.com/assets/13474364/8862298/d6449598-318f-11e5-9dd7-c52c99a8dbce.PNG)

I really appreciate any help you can provide.

**Comment by xoofx** [comment]
Thanks for the report. As the exception is not logged, we have fixed the log in the new release coming very soon so that we will be able to make a better diagnostic about this problem.
Sorry for the trouble.

**Comment by xen2** [comment]
Paradox 1.2.1 has just been released, could you give it another try (log should have more details). Thanks!

**Comment by SimonLeeroy** [comment]
Thank you. Firstly, I changed to version 1.2.1 and it seems to work properly, but only with administrative privileges. After many trials, finally I had it. However, version 1.1.4 as well as version 1.2.1 is not running without admin rights. The same errors are occuring as before. All in all here is the documentation. 

Paradox3d v.1.2.1 without admin rights
![unbenannt](https://cloud.githubusercontent.com/assets/13474364/8891264/c3dd5f68-3322-11e5-9da3-ba4e0edb86a1.png)

Paradox3d v.1.2.1 with admin rights
![unbenannt1](https://cloud.githubusercontent.com/assets/13474364/8891267/d4b2053c-3322-11e5-8164-f2236cc264a9.PNG)


Paradox3d v.1.1.4 without admin rights
![1 1 4](https://cloud.githubusercontent.com/assets/13474364/8891270/e734aa02-3322-11e5-8957-31deea66f021.PNG)

Paradox3d v.1.1.4 with admin rights
![1 1 4 working](https://cloud.githubusercontent.com/assets/13474364/8891273/f50e41e2-3322-11e5-981e-fc3d582a0f14.PNG)

**Comment by xoofx** [comment]
Could you copy-paste the exception that you get in 1.2.1-beta?

**Comment by SimonLeeroy** [comment]
Of course, here you go.
<code>[]: Info: Loading Assets from Package [Paradox.pdxpkg]
[]: Info: Loading Assets from Package [MyGame25.pdxpkg]
[]: Info: Generate MyGame25.Game
[]: Error: Unexpected exception while processing [Source: $ProjectName$.csproj.t4, Target: $ProjectName$.csproj, IsTemplate: True]. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Die Datei oder Assembly "hpzj1fxt.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Zugriff verweigert
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, Evidence assemblySecurity)
   at System.CodeDom.Compiler.CompilerResults.get_CompiledAssembly()
   at Mono.TextTemplating.CompiledTemplate.Load(CompilerResults results, String fullName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Mono.TextTemplating.TemplatingEngine.CompileTemplate(String content, ITextTemplatingEngineHost host)
   at Mono.TextTemplating.TemplatingEngine.ProcessTemplate(String content, ITextTemplatingEngineHost host)
   at SiliconStudio.ProjectTemplating.ProjectTemplate.Generate(String outputDirectory, String projectName, Guid projectGuid, ILogger log, Dictionary`2 options, List`1 generatedOutputFiles)
[]: Error: Unexpected exception while processing [Source: Properties\AssemblyInfo.cs.t4, Target: Properties\AssemblyInfo.cs, IsTemplate: True]. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Die Datei oder Assembly "42rhmfau.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Zugriff verweigert
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, Evidence assemblySecurity)
   at System.CodeDom.Compiler.CompilerResults.get_CompiledAssembly()
   at Mono.TextTemplating.CompiledTemplate.Load(CompilerResults results, String fullName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Mono.TextTemplating.TemplatingEngine.CompileTemplate(String content, ITextTemplatingEngineHost host)
   at Mono.TextTemplating.TemplatingEngine.ProcessTemplate(String content, ITextTemplatingEngineHost host)
   at SiliconStudio.ProjectTemplating.ProjectTemplate.Generate(String outputDirectory, String projectName, Guid projectGuid, ILogger log, Dictionary`2 options, List`1 generatedOutputFiles)
[]: Info: Generate MyGame25.Windows
[]: Error: Unexpected exception while processing [Source: $ProjectName$.csproj.t4, Target: $ProjectName$.csproj, IsTemplate: True]. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Die Datei oder Assembly "vsuh2pmc.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Zugriff verweigert
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, Evidence assemblySecurity)
   at System.CodeDom.Compiler.CompilerResults.get_CompiledAssembly()
   at Mono.TextTemplating.CompiledTemplate.Load(CompilerResults results, String fullName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Mono.TextTemplating.TemplatingEngine.CompileTemplate(String content, ITextTemplatingEngineHost host)
   at Mono.TextTemplating.TemplatingEngine.ProcessTemplate(String content, ITextTemplatingEngineHost host)
   at SiliconStudio.ProjectTemplating.ProjectTemplate.Generate(String outputDirectory, String projectName, Guid projectGuid, ILogger log, Dictionary`2 options, List`1 generatedOutputFiles)
[]: Error: Unexpected exception while processing [Source: $PackageNameShort$App.cs.t4, Target: $PackageNameShort$App.cs, IsTemplate: True]. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Die Datei oder Assembly "nzkto5nc.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Zugriff verweigert
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, Evidence assemblySecurity)
   at System.CodeDom.Compiler.CompilerResults.get_CompiledAssembly()
   at Mono.TextTemplating.CompiledTemplate.Load(CompilerResults results, String fullName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Mono.TextTemplating.TemplatingEngine.CompileTemplate(String content, ITextTemplatingEngineHost host)
   at Mono.TextTemplating.TemplatingEngine.ProcessTemplate(String content, ITextTemplatingEngineHost host)
   at SiliconStudio.ProjectTemplating.ProjectTemplate.Generate(String outputDirectory, String projectName, Guid projectGuid, ILogger log, Dictionary`2 options, List`1 generatedOutputFiles)
[]: Error: Unexpected exception while processing [Source: Properties\AssemblyInfo.cs.t4, Target: Properties\AssemblyInfo.cs, IsTemplate: True]. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Die Datei oder Assembly "2hshyulx.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Zugriff verweigert
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, Evidence assemblySecurity)
   at System.CodeDom.Compiler.CompilerResults.get_CompiledAssembly()
   at Mono.TextTemplating.CompiledTemplate.Load(CompilerResults results, String fullName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Mono.TextTemplating.TemplatingEngine.CompileTemplate(String content, ITextTemplatingEngineHost host)
   at Mono.TextTemplating.TemplatingEngine.ProcessTemplate(String content, ITextTemplatingEngineHost host)
   at SiliconStudio.ProjectTemplating.ProjectTemplate.Generate(String outputDirectory, String projectName, Guid projectGuid, ILogger log, Dictionary`2 options, List`1 generatedOutputFiles)
[]: Info: Loading Assets from Package [MyGame25.pdxpkg]
</code>

---> System.IO.FileLoadException: Die Datei oder Assembly "hpzj1fxt.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Zugriff verweigert
   at System.Reflection.RuntimeAssembly
**de to en translation:**

---> System.IO.FileLoadException: The file or assembly "hpzj1fxt.dll" or dependencies were not found. Access denied at System.Reflection.RuntimeAssembly ...

**Comment by xoofx** [comment]
Hi,
I'm currently working on fixing this, but I can only see that the template compiler is trying to load/write to a temp folder, which should be standard and writeable on Windows machine, but it seems not to be your case.
Could you create a small Console app:

```C#
using System;
namespace CheckPathTempApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(System.IO.Path.GetTempPath());
        }
    }
}
```
And check which folder is outputted and make sure that you have write access to these folders? (remove everything from it for example)
