### ISSUE TITLE
NullPointerException on Android when sound is muted

### ISSUE THREAD

**Issue by dannyd89** [SiliconStudio/xenko#323]
Basiclly every sample or own created project did crash for me when I tried to start an app on Android (build with the latest Xamarin).

Running in Debug mode I get the following exception
```csharp
10-22 19:40:38.025 I/MonoDroid( 5460): UNHANDLED EXCEPTION:
10-22 19:40:38.055 I/MonoDroid( 5460): Java.Lang.NullPointerException: Exception of type 'Java.Lang.NullPointerException' was thrown.
10-22 19:40:38.055 I/MonoDroid( 5460): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/2185/53fce373/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61
10-22 19:40:38.055 I/MonoDroid( 5460): at Android.Runtime.JNIEnv.CallVoidMethod (intptr,intptr,Android.Runtime.JValue*) <IL 0x00069, 0x002a3>
10-22 19:40:38.055 I/MonoDroid( 5460): at Android.Media.AudioManager.SetStreamMute (Android.Media.Stream,bool) <IL 0x00079, 0x00353>
10-22 19:40:38.055 I/MonoDroid( 5460): at SiliconStudio.Paradox.Starter.AndroidParadoxActivity/RingerModeIntentReceiver.UpdateMusicMuteStatus () <IL 0x0004e, 0x001d3>
10-22 19:40:38.055 I/MonoDroid( 5460): at SiliconStudio.Paradox.Starter.AndroidParadoxActivity/RingerModeIntentReceiver.OnReceive (Android.Content.Context,Android.Content.Intent) <IL 0x00001, 0x0004b>
10-22 19:40:38.055 I/MonoDroid( 5460): at Android.Content.BroadcastReceiver.n_OnReceive_Landroid_content_Context_Landroid_content_Intent_ (intptr,intptr,intptr,intptr) <IL 0x0001c, 0x00147>
10-22 19:40:38.055 I/MonoDroid( 5460): at (wrapper dynamic-method) object.a5c32780-f32d-441c-bd5e-28314003e1b3 (intptr,intptr,intptr,intptr) <IL 0x0001d, 0x0004b>
10-22 19:40:38.055 I/MonoDroid( 5460):   --- End of managed exception stack trace ---
10-22 19:40:38.055 I/MonoDroid( 5460): java.lang.NullPointerException: Null pointer exception during instruction 'invoke-static {v0}, android.os.IBinder android.media.AudioService$VolumeStreamState$VolumeDeathHandler.access$5300(android.media.AudioService$VolumeStreamState$VolumeDeathHandler) // method@11515'
10-22 19:40:38.055 I/MonoDroid( 5460): 	at android.os.Parcel.readException(Parcel.java:1546)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at android.os.Parcel.readException(Parcel.java:1493)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at android.media.IAudioService$Stub$Proxy.setStreamMute(IAudioService.java:992)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at android.media.AudioManager.setStreamMute(AudioManager.java:1465)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at md59233111163ee94d7cc38d0d4086a08ef.AndroidParadoxActivity_RingerModeIntentReceiver.n_onReceive(Native Method)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at md59233111163ee94d7cc38d0d4086a08ef.AndroidParadoxActivity_RingerModeIntentReceiver.onReceive(AndroidParadoxActivity_RingerModeIntentReceiver.java:35)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:923)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at android.os.Handler.handleCallback(Handler.java:739)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at android.os.Looper.loop(Looper.java:145)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at android.app.ActivityThread.main(ActivityThread.java:5832)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at java.lang.reflect.Method.invoke(Native Method)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at java.lang.reflect.Method.invoke(Method.java:372)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
10-22 19:40:38.055 I/MonoDroid( 5460): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```
Reading it I figured that I might be cause of my sound being muted on the phone, after I turned the sound on, the app didn't crash anymore. Maybe it's something related to the new Android versions?

**Comment by xenux** [comment]
Hi! 

thanks for the report, unfortunately I could not reproduce the problem. 
Could you indicate me which version of Anroid and xamarin as well as which device do you have?

Thanks in advance.
