### ISSUE TITLE
[1.4.2] FormatException when creating a new built-in sample project

### ISSUE THREAD

**Issue by discosultan** [SiliconStudio/xenko#340]
I ran into `FormatException` when creating a new Material Shader sample project:

```
[]: Error: Error while loading package [e835275a-a0d3-4785-aa95-785be48965ce]. System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToSingle(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at SiliconStudio.Core.Yaml.DynamicYamlScalar.TryConvert(ConvertBinder binder, Object& result) in C:\TeamCity\work\e6f0ed62352ac70f\sources\common\core\SiliconStudio.Core.Design\Yaml\DynamicYamlScalar.cs:line 32
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SiliconStudio.Xenko.Assets.ProceduralModels.ProceduralModelAsset.Standardization.UpgradeAsset(AssetMigrationContext context, PackageVersion currentVersion, PackageVersion targetVersion, Object asset, PackageLoadingAssetFile assetFile) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Assets\ProceduralModels\ProceduralModelAsset.cs:line 152
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at SiliconStudio.Assets.AssetUpgraderBase.Upgrade(AssetMigrationContext context, String dependencyName, PackageVersion currentVersion, PackageVersion targetVersion, YamlMappingNode yamlAssetNode, PackageLoadingAssetFile assetFile) in C:\TeamCity\work\e6f0ed62352ac70f\sources\assets\SiliconStudio.Assets\AssetUpgraderBase.cs:line 18
   at SiliconStudio.Assets.AssetMigration.MigrateAssetIfNeeded(AssetMigrationContext context, PackageLoadingAssetFile loadAsset, String dependencyName, PackageVersion untilVersion) in C:\TeamCity\work\e6f0ed62352ac70f\sources\assets\SiliconStudio.Assets\AssetMigration.cs:line 162
   at SiliconStudio.Xenko.Assets.XenkoPackageUpgrader.RunAssetUpgradersUntilVersion(ILogger log, Package dependentPackage, String dependencyName, IList`1 assetFiles, PackageVersion maxVersion) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Assets\XenkoPackageUpgrader.cs:line 120
   at SiliconStudio.Xenko.Assets.XenkoPackageUpgrader.Upgrade(PackageSession session, ILogger log, Package dependentPackage, PackageDependency dependency, Package dependencyPackage, IList`1 assetFiles) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Assets\XenkoPackageUpgrader.cs:line 109
   at SiliconStudio.Assets.PackageSession.TryLoadAssets(PackageSession session, ILogger log, Package package, PackageLoadParameters loadParameters) in C:\TeamCity\work\e6f0ed62352ac70f\sources\assets\SiliconStudio.Assets\PackageSession.cs:line 1121
[]: Error: Could not find game settings asset at location [GameSettings]
```

This happened on a machine with Norwegian date/time/number format.
I have not tested any other project templates and I don't have any previous installations of the engine.

Here is the full log:

```
[]: Verbose: C:\Users\VarusJ\AppData\Local\Programs\Silicon Studio\Xenko\GamePackages\Xenko.1.4.2-beta\Templates\Samples\Graphics\MaterialShader\MaterialShader.xkpkg needs update, from version 0.0.1 to version 0.0.2
[]: Info: C:\Users\VarusJ\AppData\Local\Programs\Silicon Studio\Xenko\GamePackages\Xenko.1.4.2-beta\Templates\Samples\Graphics\MaterialShader\MaterialShader.xkpkg updated from version 0.0.1 to version 0.0.2
[]: Verbose: C:\Users\VarusJ\Code\xenko\MaterialShader\MaterialShader\MaterialShader.xkpkg needs update, from version 0.0.1 to version 0.0.2
[]: Info: C:\Users\VarusJ\Code\xenko\MaterialShader\MaterialShader\MaterialShader.xkpkg updated from version 0.0.1 to version 0.0.2
[]: Info: Loading Assets from Package [Xenko.xkpkg]
[]: Info: Upgrading package [MaterialShader] to use [Xenko] from version [1.3.0-beta] to [1.4.2-beta] will be required
[]: Verbose: C:\Users\VarusJ\Code\xenko\MaterialShader\MaterialShader\Assets\Shared\Material.xkmat needs update, from version 0.0.1 to version 1.4.0-beta
[]: Info: C:\Users\VarusJ\Code\xenko\MaterialShader\MaterialShader\Assets\Shared\Material.xkmat updated from version 0.0.1 to version 1.4.0-beta
[]: Verbose: C:\Users\VarusJ\Code\xenko\MaterialShader\MaterialShader\Assets\Shared\PlaneModel.xkpromodel needs update, from version 0.0.4 to version 1.4.0-beta
[]: Error: Error while loading package [e835275a-a0d3-4785-aa95-785be48965ce]. System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToSingle(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at SiliconStudio.Core.Yaml.DynamicYamlScalar.TryConvert(ConvertBinder binder, Object& result) in C:\TeamCity\work\e6f0ed62352ac70f\sources\common\core\SiliconStudio.Core.Design\Yaml\DynamicYamlScalar.cs:line 32
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SiliconStudio.Xenko.Assets.ProceduralModels.ProceduralModelAsset.Standardization.UpgradeAsset(AssetMigrationContext context, PackageVersion currentVersion, PackageVersion targetVersion, Object asset, PackageLoadingAssetFile assetFile) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Assets\ProceduralModels\ProceduralModelAsset.cs:line 152
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at SiliconStudio.Assets.AssetUpgraderBase.Upgrade(AssetMigrationContext context, String dependencyName, PackageVersion currentVersion, PackageVersion targetVersion, YamlMappingNode yamlAssetNode, PackageLoadingAssetFile assetFile) in C:\TeamCity\work\e6f0ed62352ac70f\sources\assets\SiliconStudio.Assets\AssetUpgraderBase.cs:line 18
   at SiliconStudio.Assets.AssetMigration.MigrateAssetIfNeeded(AssetMigrationContext context, PackageLoadingAssetFile loadAsset, String dependencyName, PackageVersion untilVersion) in C:\TeamCity\work\e6f0ed62352ac70f\sources\assets\SiliconStudio.Assets\AssetMigration.cs:line 162
   at SiliconStudio.Xenko.Assets.XenkoPackageUpgrader.RunAssetUpgradersUntilVersion(ILogger log, Package dependentPackage, String dependencyName, IList`1 assetFiles, PackageVersion maxVersion) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Assets\XenkoPackageUpgrader.cs:line 120
   at SiliconStudio.Xenko.Assets.XenkoPackageUpgrader.Upgrade(PackageSession session, ILogger log, Package dependentPackage, PackageDependency dependency, Package dependencyPackage, IList`1 assetFiles) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Assets\XenkoPackageUpgrader.cs:line 109
   at SiliconStudio.Assets.PackageSession.TryLoadAssets(PackageSession session, ILogger log, Package package, PackageLoadParameters loadParameters) in C:\TeamCity\work\e6f0ed62352ac70f\sources\assets\SiliconStudio.Assets\PackageSession.cs:line 1121
[]: Error: Could not find game settings asset at location [GameSettings]


```

**Comment by sinkingsugar** [comment]
Thanks for the report.. It definitely was a bug on our side, missing an invariant culture flag.
