### ISSUE TITLE
Can't add any built-in scripts to a project

### ISSUE THREAD

**Issue by EternalTamago** [SiliconStudio/xenko#342]
Hello!

Script source code's operation can't add any built-in scripts to a project when there is an interface that is defined in the project.

[TestScript.cs]
```
using SiliconStudio.Xenko.Engine;

namespace MyGame2
{
    public class TestScript : SyncScript
    {
        interface IMyTest
        {
            void MyMethod();
        }
        public override void Update()
        {
        }
    }
}
```

The operation get also same result in the below case.

[IMyTest.cs]
```
namespace MyGame2
{
    interface IMyTest
    {
        void MyMethod();
    }
}
```

[Information about the crash]
```
Xenko Version: 1.5.0-beta
GameStudio Version: 4
Default session graphics profile: Level_10_0
Current Directory: D:\Data\Xenko Projects\MyGame2\MyGame2\MyGame2.Game
Command Line Args: D:\Data\Xenko Projects\MyGame2\MyGame2.sln
OS Version: Microsoft Windows NT 6.2.9200.0 (x64)
Processor Count: 4
Video configuration:
GPU 1
BitsPerPel: 32
Caption: NVIDIA GeForce GTX 660  
Description: NVIDIA GeForce GTX 660  
DeviceName: NVIDIA GeForce GTX 660  
DisplayFlags: 0
DisplayFrequency: 60
DitherType: 
DriverVersion: 
ICMIntent: 
ICMMethod: 
LogPixels: 96
PelsHeight: 768
PelsWidth: 1024
SettingID: NVIDIA GeForce GTX 660  
SpecificationVersion: 1025
Exception: NullReferenceException: Object reference not set to an instance of an object.
   at SiliconStudio.Xenko.Assets.Presentation.ViewModel.ScriptSourceFileCreationView.<Create>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SiliconStudio.Assets.Editor.ViewModel.AssetFactoryViewModel.<CreateAsset>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at SiliconStudio.Xenko.GameStudio.Program.Main()
```
Xenko 1.5.0-beta / Launcher v1.4.2
Windows 10 Pro x64

**Comment by sinkingsugar** [comment]
Thanks for the report, it is already fixed internally! Expect a release soon with a fix.
