### ISSUE TITLE
[Bug 1.5.1] XenkoDefaultFont could not be found when using GameProfiler script

### ISSUE THREAD

**Issue by LennyPenny** [SiliconStudio/xenko#345]
When attaching the new GameProfiler script to an entity in the Scene and pressing lctrl+lshift+p ingame the game crashes with this error stating that the XenkoDefaultFont could not be found. 
I looked into the installation directory with all the default assets and indeed it's not there. 

```
[Profiler] #1799: Begin: Asset.Load: XenkoDefaultFont
[AssetManager]: Error: The asset 'XenkoDefaultFont' could not be found. Asset pa
th should be 'MyFolder/MyAssetName'. Check that the path is correct and that the
 asset has been included into the build.
[Profiler] #1799: End: Asset.Load: XenkoDefaultFont: Elapsed = 26.860ms
[Game]: Error: Unexpected exception. System.ArgumentNullException: Value cannot
be null.
Parameter name: spriteFont
   at SiliconStudio.Xenko.Graphics.SpriteBatch.DrawString(SpriteFont spriteFont,
 StringProxy& text, Single fontSize, Vector2& position, Color4& color, Single ro
tation, Vector2& origin, Vector2& scale, SpriteEffects effects, Single layerDept
h, TextAlignment alignment) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\
SiliconStudio.Xenko.Graphics\SpriteBatch.cs:line 479
   at SiliconStudio.Xenko.Graphics.SpriteBatch.DrawString(SpriteFont spriteFont,
 StringProxy& text, Single fontSize, Vector2& position, Color4& color, Single ro
tation, Vector2 origin, Vector2 scale, SpriteEffects effects, Single layerDepth,
 TextAlignment alignment) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\Si
liconStudio.Xenko.Graphics\SpriteBatch.cs:line 472
   at SiliconStudio.Xenko.Graphics.SpriteBatch.DrawString(SpriteFont spriteFont,
 String text, Vector2 position, Color4 color, TextAlignment alignment) in C:\Tea
mCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Graphics\SpriteBa
tch.cs:line 359
   at SiliconStudio.Xenko.Profiling.GameProfilingSystem.Draw(GameTime gameTime)
in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\P
rofiling\GameProfilerSystem.cs:line 297
   at SiliconStudio.Xenko.Games.GameSystemCollection.Draw(GameTime gameTime) in
C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Games\GameS
ystemCollection.cs:line 125
   at SiliconStudio.Xenko.Games.GameBase.Draw(GameTime gameTime) in C:\TeamCity\
work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line
738
   at SiliconStudio.Xenko.Games.GameBase.DrawFrame() in C:\TeamCity\work\e6f0ed6
2352ac70f\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 920
   at SiliconStudio.Xenko.Games.GameBase.TickInternal() in C:\TeamCity\work\e6f0
ed62352ac70f\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 636
System.ArgumentNullException: Value cannot be null.
Parameter name: spriteFont
   at SiliconStudio.Xenko.Graphics.SpriteBatch.DrawString(SpriteFont spriteFont,
 StringProxy& text, Single fontSize, Vector2& position, Color4& color, Single ro
tation, Vector2& origin, Vector2& scale, SpriteEffects effects, Single layerDept
h, TextAlignment alignment) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\
SiliconStudio.Xenko.Graphics\SpriteBatch.cs:line 479
   at SiliconStudio.Xenko.Graphics.SpriteBatch.DrawString(SpriteFont spriteFont,
 StringProxy& text, Single fontSize, Vector2& position, Color4& color, Single ro
tation, Vector2 origin, Vector2 scale, SpriteEffects effects, Single layerDepth,
 TextAlignment alignment) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\Si
liconStudio.Xenko.Graphics\SpriteBatch.cs:line 472
   at SiliconStudio.Xenko.Graphics.SpriteBatch.DrawString(SpriteFont spriteFont,
 String text, Vector2 position, Color4 color, TextAlignment alignment) in C:\Tea
mCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Graphics\SpriteBa
tch.cs:line 359
   at SiliconStudio.Xenko.Profiling.GameProfilingSystem.Draw(GameTime gameTime)
in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\P
rofiling\GameProfilerSystem.cs:line 297
   at SiliconStudio.Xenko.Games.GameSystemCollection.Draw(GameTime gameTime) in
C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Games\GameS
ystemCollection.cs:line 125
   at SiliconStudio.Xenko.Games.GameBase.Draw(GameTime gameTime) in C:\TeamCity\
work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line
738
   at SiliconStudio.Xenko.Games.GameBase.DrawFrame() in C:\TeamCity\work\e6f0ed6
2352ac70f\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 920
   at SiliconStudio.Xenko.Games.GameBase.TickInternal() in C:\TeamCity\work\e6f0
ed62352ac70f\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 636

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: spriteFont
   at SiliconStudio.Xenko.Graphics.SpriteBatch.DrawString(SpriteFont spriteFont,
 StringProxy& text, Single fontSize, Vector2& position, Color4& color, Single ro
tation, Vector2& origin, Vector2& scale, SpriteEffects effects, Single layerDept
h, TextAlignment alignment) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\
SiliconStudio.Xenko.Graphics\SpriteBatch.cs:line 479
   at SiliconStudio.Xenko.Graphics.SpriteBatch.DrawString(SpriteFont spriteFont,
 StringProxy& text, Single fontSize, Vector2& position, Color4& color, Single ro
tation, Vector2 origin, Vector2 scale, SpriteEffects effects, Single layerDepth,
 TextAlignment alignment) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\Si
liconStudio.Xenko.Graphics\SpriteBatch.cs:line 472
   at SiliconStudio.Xenko.Graphics.SpriteBatch.DrawString(SpriteFont spriteFont,
 String text, Vector2 position, Color4 color, TextAlignment alignment) in C:\Tea
mCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Graphics\SpriteBa
tch.cs:line 359
   at SiliconStudio.Xenko.Profiling.GameProfilingSystem.Draw(GameTime gameTime)
in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\P
rofiling\GameProfilerSystem.cs:line 297
   at SiliconStudio.Xenko.Games.GameSystemCollection.Draw(GameTime gameTime) in
C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Games\GameS
ystemCollection.cs:line 125
   at SiliconStudio.Xenko.Games.GameBase.Draw(GameTime gameTime) in C:\TeamCity\
work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line
738
   at SiliconStudio.Xenko.Games.GameBase.DrawFrame() in C:\TeamCity\work\e6f0ed6
2352ac70f\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 920
   at SiliconStudio.Xenko.Games.GameBase.TickInternal() in C:\TeamCity\work\e6f0
ed62352ac70f\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 657
   at SiliconStudio.Xenko.Games.GameBase.Tick() in C:\TeamCity\work\e6f0ed62352a
c70f\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 494
   at SiliconStudio.Xenko.Games.GamePlatform.Tick() in C:\TeamCity\work\e6f0ed62
352ac70f\sources\engine\SiliconStudio.Xenko.Games\GamePlatform.cs:line 175
   at SiliconStudio.Xenko.Games.GamePlatform.OnRunCallback() in C:\TeamCity\work
\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Games\GamePlatform.cs:line
145
   at SiliconStudio.Xenko.Games.GameWindowWinforms.<>c__DisplayClass19_0.<Run>b_
_0() in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Gam
es\Desktop\GameWindow.Windows.Desktop.cs:line 217
   at SiliconStudio.Xenko.Games.WindowsMessageLoop.Run(Control form, RenderCallb
ack renderCallback, Boolean useApplicationDoEvents) in C:\TeamCity\work\e6f0ed62
352ac70f\sources\engine\SiliconStudio.Xenko.Games\Desktop\WindowsMessageLoop.cs:
line 233
   at SiliconStudio.Xenko.Games.GameWindowWinforms.Run() in C:\TeamCity\work\e6f
0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Games\Desktop\GameWindow.Window
s.Desktop.cs:line 209
   at SiliconStudio.Xenko.Games.GamePlatform.Run(GameContext gameContext) in C:\
TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Games\GamePlat
form.cs:line 122
   at SiliconStudio.Xenko.Games.GameBase.Run(GameContext gameContext) in C:\Team
City\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:
line 453
   at Hover2.Hover2App.Main(String[] args) in C:\Users\Lenny\Documents\Xenko Pro
jects\Hover2\Hover2\Hover2.Windows\Hover2App.cs:line 11
```

**Comment by sinkingsugar** [comment]
Thanks! I will check now. The default found might not be included in the package indeed...

**Comment by sinkingsugar** [comment]
It indeed was missing in the nuget build process. nice catch! Will be fixed in the next release.

**Comment by boriscallens** [comment]
Is there a file we can place somewhere in the meantime?

**Comment by boriscallens** [comment]
For people wanting to work around this before a fix is released:
- add a spritefont to your assets and mark it as build for root)
- add the following line to your profiler script's execute (not in the loop):
 
game.ProfilerSystem.Font = game.Asset.Load<SpriteFont>("ProfilerFont");
