### ISSUE TITLE
[Bug 1.5.1] Error when trying to create a ConvexHull ColliderShape from any model

### ISSUE THREAD

**Issue by LennyPenny** [SiliconStudio/xenko#346]
I tested it with 2 different models on different model formats (FBX and obj). 

```
[]: Error: Exception in command 0280475e-ca0d-4d74-b5d8-bf40271ac411: System.NullReferenceException: Object reference not set to an instance of an object.
   at SiliconStudio.Xenko.Assets.Physics.ColliderShapeAssetCompiler.ColliderShapeCombineCommand.DoCommandOverride(ICommandContext commandContext) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Assets\Physics\ColliderShapeAssetCompiler.cs:line 97
   at SiliconStudio.BuildEngine.Command.DoCommand(ICommandContext commandContext) in C:\TeamCity\work\e6f0ed62352ac70f\sources\common\buildengine\SiliconStudio.BuildEngine.Common\Command.cs:line 80
   at SiliconStudio.BuildEngine.CommandBuildStep.<StartCommand>d__21.MoveNext() in C:\TeamCity\work\e6f0ed62352ac70f\sources\common\buildengine\SiliconStudio.BuildEngine.Common\CommandBuildStep.cs:line 446
[C:/Users/Lenny/Documents/Xenko Projects/Hover2/Hover2/Assets/Shared/HoverJet2/ColliderShape.xkphy(1,1)]: Error: BuildStep 0280475e-ca0d-4d74-b5d8-bf40271ac411 failed.
[]: Error: Exception in command 0280475e-ca0d-4d74-b5d8-bf40271ac411: System.NullReferenceException: Object reference not set to an instance of an object.
   at SiliconStudio.Xenko.Assets.Physics.ColliderShapeAssetCompiler.ColliderShapeCombineCommand.DoCommandOverride(ICommandContext commandContext) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Assets\Physics\ColliderShapeAssetCompiler.cs:line 97
   at SiliconStudio.BuildEngine.Command.DoCommand(ICommandContext commandContext) in C:\TeamCity\work\e6f0ed62352ac70f\sources\common\buildengine\SiliconStudio.BuildEngine.Common\Command.cs:line 80
   at SiliconStudio.BuildEngine.CommandBuildStep.<StartCommand>d__21.MoveNext() in C:\TeamCity\work\e6f0ed62352ac70f\sources\common\buildengine\SiliconStudio.BuildEngine.Common\CommandBuildStep.cs:line 446
[]: Error: Asset [HoverJet2/ColliderShape] failed to compile
[C:/Users/Lenny/Documents/Xenko Projects/Hover2/Hover2/Assets/Shared/HoverJet2/ColliderShape.xkphy(1,1)]: Error: BuildStep Asset build steps [ColliderShapeAsset:'HoverJet2/ColliderShape'] (1 items) failed.
[]: Error: BuildStep Build step list (302 items) failed.
[]: Error: BuildStep Build step list (1 items) failed.
[]: Error: Build finished in 598 steps. Command results: 10 succeeded, 584 up-to-date, 4 failed, 0 not triggered due to previous failure.
[]: Error: Build failed.
```

**Comment by sinkingsugar** [comment]
Already solved in the master branch.

**Comment by sinkingsugar** [comment]
Sorry, I was on the train and I answered too quickly but yeah... I forgot to test convex hull generation compatibility with the new skeleton system and it definitely did not work.
Thanks for the report. It will be pushed in the next release! I hope it won't slow down your workflow without hulls for a few.
