### ISSUE TITLE
[1.6.1] Xenko crashes at start because of WPF-error

### ISSUE THREAD

**Issue by NineBytes** [SiliconStudio/xenko#377]
Hi,

Everytime when i start the GameStudio i get a "Report the crash"-window. Unfortunately i can't send the report on this way.

Here is the report:
Application: GameStudio
UserEmail: phoenix2436@gmail.com
UserMessage: 
XenkoVersion: 1.6.1-beta
GameStudioVersion: 4
DefaultGraphicProfile: Level_10_0
CurrentDirectory:****
CommandArgs: /LauncherWindowHandle 328906 ****
OsVersion: Microsoft Windows NT 6.2.9200.0 x64
ProcessorCount: 4
Exception: InvalidOperationException: Interner Fehler: Vom internen WPF-Code wurde versucht, eine "BindingExpression" zu reaktivieren, die bereits als getrennt markiert war.
   at System.Windows.Data.BindingExpressionBase.SetStatus(BindingStatusInternal status)
   at MS.Internal.Data.ClrBindingWorker.SetStatus(PropertyPathStatus status)
   at MS.Internal.Data.ClrBindingWorker.CompleteGetValue(AsyncGetValueRequest request)
   at MS.Internal.Data.ClrBindingWorker.OnCompleteGetValueOperation(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at SiliconStudio.Xenko.GameStudio.Program.Main()

GPU0.AdapterCompatibility: NVIDIA
GPU0.AdapterDACType: Integrated RAMDAC
GPU0.AdapterRAM: 2147483648
GPU0.Availability: 3
GPU0.Caption: NVIDIA GeForce GT 520 
GPU0.ConfigManagerErrorCode: 0
GPU0.ConfigManagerUserConfig: False
GPU0.CreationClassName: Win32_VideoController
GPU0.CurrentBitsPerPixel: 32
GPU0.CurrentHorizontalResolution: 1024
GPU0.CurrentNumberOfColors: 4294967296
GPU0.CurrentNumberOfColumns: 0
GPU0.CurrentNumberOfRows: 0
GPU0.CurrentRefreshRate: 60
GPU0.CurrentScanMode: 4
GPU0.CurrentVerticalResolution: 768
GPU0.Description: NVIDIA GeForce GT 520 
GPU0.DeviceID: VideoController1
GPU0.DitherType: 0
GPU0.DriverDate: 20160223000000.000000-000
GPU0.DriverVersion: 10.18.13.6200
GPU0.InfFilename: oem39.inf
GPU0.InfSection: Section001
GPU0.InstalledDisplayDrivers: nvd3dumx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvd3dum,nvwgf2um,nvwgf2um,nvwgf2um
GPU0.MaxRefreshRate: 60
GPU0.MinRefreshRate: 50
GPU0.Monochrome: False
GPU0.Name: NVIDIA GeForce GT 520 
GPU0.PNPDeviceID: PCI\VEN_10DE&DEV_1040&SUBSYS_00000000&REV_A1\4&2E9A8D61&0&0008
GPU0.Status: OK
GPU0.SystemCreationClassName: Win32_ComputerSystem
GPU0.SystemName: ****
GPU0.VideoArchitecture: 5
GPU0.VideoMemoryType: 2
GPU0.VideoModeDescription: 1024 x 768 x 4294967296 Farben
GPU0.VideoProcessor: GeForce GT 520

I hope someone can help (me)

**Comment by Kryptos-FR** [comment]
Did you try reinstalling (could be some dependencies issues)? Have you had any problems with older version of Xenko?

**Comment by Benlitz** [comment]
Hello,

We pushed a potential fix on the version 1.6.2. Could you update your version of Xenko (from the launcher) try again?

**Comment by NineBytes** [comment]
yes version 1.6.2 fixed my problem. thank you :)

2016-04-19 11:02 GMT+02:00 Benlitz <notifications@github.com>:
