### ISSUE TITLE
System.IO.FileLoadException when building game (1.6.5-beta)

### ISSUE THREAD

**Issue by artganify** [SiliconStudio/xenko#410]
Starting from `1.6.5-beta` (and up to `1.6.6-beta`), I'm unable to build any game anymore. During build, Xenko crashes with a `System.IO.FileLoadException` while attempting to load `SiliconStudio.Xenko.Importer.Assimp.DLL`.

Steps to reproduce:

1. Create new Xenko empty game (*New Game*) project
2. After initialization, build without changes (F5)

Output:

	[(0,0)]: Info: Assembly [TestProject.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] has already been processed, skip it.
	[(0,0)]: Info: TestProject.Game -> C:\Users\USERNAME\Desktop\TestProject\src\TestProject\Bin\Windows\Debug\TestProject.Game.dll
	[(0,0)]: Info: Assembly [TestProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] has already been processed, skip it.
	[(0,0)]: Info: TestProject.Windows -> C:\Users\USERNAME\Desktop\TestProject\src\TestProject\Bin\Windows\Debug\TestProject.exe
	[]: Info: BuildEngine arguments: --disable-auto-compile --project-configuration Debug --platform=Windows --graphics-platform=Direct3D11 --profile=Windows --project-configuration=Debug --output-path=C:\Users\USERNAME\Desktop\TestProject\src\TestProject\Bin\Windows\Debug\data --build-path=C:\Users\USERNAME\Desktop\TestProject\src\TestProject\TestProject.Windows\..\obj\data --package-file=C:\Users\USERNAME\Desktop\TestProject\src\TestProject\TestProject.Windows\..\TestProject.xkpkg --log-pipe=net.pipe://localhost/SiliconStudio.Assets.Editor.b43c5ee5-baf3-404b-9c5f-f91cf471dd12 --verbose
	[]: Info: Starting builder.
	[]: Error: Unhandled exception: Error while loading default package from [C:/Users/USERNAME/AppData/Local/Programs/Silicon Studio/Xenko/GamePackages/Xenko.1.6.6-beta\Xenko.xkpkg]: []: Error: Error while pre-loading package [C:\Users\USERNAME\AppData\Local\Programs\Silicon Studio\Xenko\GamePackages\Xenko.1.6.6-beta\Xenko.xkpkg]. System.IO.FileLoadException: Could not load file or assembly 'SiliconStudio.Xenko.Importer.Assimp.DLL' or one of its dependencies. The filename or extension is too long.
	File name: 'SiliconStudio.Xenko.Importer.Assimp.DLL'
	   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
	   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
	   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
	   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
	   at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
	   at SharpYaml.Serialization.AttributeRegistry.GetAttributes(MemberInfo memberInfo, Boolean inherit)
	   at SharpYaml.Serialization.AssemblyRegistry.RegisterAssembly(Assembly assembly, IAttributeRegistry attributeRegistry)
	   at SiliconStudio.Core.Yaml.YamlSerializer.CreateSerializer(Serializer& localSerializer, Boolean generateIds) in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core.Design\Yaml\YamlSerializer.cs:line 257
	   at SiliconStudio.Core.Yaml.YamlSerializer.GetYamlSerializer(Boolean generateIds) in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core.Design\Yaml\YamlSerializer.cs:line 232
	   at SiliconStudio.Assets.AssetMigration.MigrateAssetIfNeeded(AssetMigrationContext context, PackageLoadingAssetFile loadAsset, String dependencyName, PackageVersion untilVersion) in C:\TeamCity\work\e71632f3cedbf5cf\sources\assets\SiliconStudio.Assets\AssetMigration.cs:line 56
	   at SiliconStudio.Assets.Package.LoadRaw(ILogger log, String filePath) in C:\TeamCity\work\e71632f3cedbf5cf\sources\assets\SiliconStudio.Assets\Package.cs:line 718

	 Exception: Error while loading default package from [C:/Users/USERNAME/AppData/Local/Programs/Silicon Studio/Xenko/GamePackages/Xenko.1.6.6-beta\Xenko.xkpkg]: []: Error: Error while pre-loading package [C:\Users\USERNAME\AppData\Local\Programs\Silicon Studio\Xenko\GamePackages\Xenko.1.6.6-beta\Xenko.xkpkg]. System.IO.FileLoadException: Could not load file or assembly 'SiliconStudio.Xenko.Importer.Assimp.DLL' or one of its dependencies. The filename or extension is too long.
	File name: 'SiliconStudio.Xenko.Importer.Assimp.DLL'
	   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
	   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
	   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
	   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
	   at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
	   at SharpYaml.Serialization.AttributeRegistry.GetAttributes(MemberInfo memberInfo, Boolean inherit)
	   at SharpYaml.Serialization.AssemblyRegistry.RegisterAssembly(Assembly assembly, IAttributeRegistry attributeRegistry)
	   at SiliconStudio.Core.Yaml.YamlSerializer.CreateSerializer(Serializer& localSerializer, Boolean generateIds) in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core.Design\Yaml\YamlSerializer.cs:line 257
	   at SiliconStudio.Core.Yaml.YamlSerializer.GetYamlSerializer(Boolean generateIds) in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core.Design\Yaml\YamlSerializer.cs:line 232
	   at SiliconStudio.Assets.AssetMigration.MigrateAssetIfNeeded(AssetMigrationContext context, PackageLoadingAssetFile loadAsset, String dependencyName, PackageVersion untilVersion) in C:\TeamCity\work\e71632f3cedbf5cf\sources\assets\SiliconStudio.Assets\AssetMigration.cs:line 56
	   at SiliconStudio.Assets.Package.LoadRaw(ILogger log, String filePath) in C:\TeamCity\work\e71632f3cedbf5cf\sources\assets\SiliconStudio.Assets\Package.cs:line 718

	[C:\Users\USERNAME\AppData\Local\Programs\Silicon Studio\Xenko\GamePackages\Xenko.1.6.6-beta\Targets\Xenko.targets(256,5)]: Error: The command ""C:\Users\USERNAME\AppData\Local\Programs\Silicon Studio\Xenko\GamePackages\Xenko.1.6.6-beta\Bin\Windows-Direct3D11\SiliconStudio.Assets.CompilerClient.exe"  --disable-auto-compile --project-configuration "Debug" --platform=Windows --graphics-platform=Direct3D11 --profile=Windows --project-configuration=Debug --output-path="C:\Users\USERNAME\Desktop\TestProject\src\TestProject\Bin\Windows\Debug\data" --build-path="C:\Users\USERNAME\Desktop\TestProject\src\TestProject\TestProject.Windows\..\obj\data" --package-file="C:\Users\USERNAME\Desktop\TestProject\src\TestProject\TestProject.Windows\..\TestProject.xkpkg" --log-pipe="net.pipe://localhost/SiliconStudio.Assets.Editor.b43c5ee5-baf3-404b-9c5f-f91cf471dd12" --verbose" exited with code 1.

**Comment by xen2** [comment]
`The filename or extension is too long.`: unfortunately windows has a 260 character limit for path.

You likely have a longer than usual username. As a workaround, can you please try to reinstall Xenko in another folder? (in a path with a shorter total length)

**Comment by artganify** [comment]
I cannot confirm this as to be the problem. First, my Windows account name / username is the same as the one on github (artganify). If that's too long, would you mind if I go by xen1 from now on? :wink: 

Second, the problem appears exclusively on Xenko versions `1.6.5-beta` and up, irregardless of where a) the main Xenko installation or b) created projects are located. I've made a clean reinstall of Xenko to path *C:\Xenko\*, also I tried to create projects in various locations (*C:\* root, desktop..)

I can create and build projects with Xenko 1.5.*-beta just fine from any installation path or project location path.

**Comment by xen2** [comment]
Yes, as said previously, we do sometime build temporary paths that build this limit (probably adds 100+ characters in some case, so even with 15+ username it might happen).

We already fixed it in our branches and will be part of next 1.6.7.

Installing Xenko itself in a shorter path is suppose to workaround the issue, but you seem to say it didn't help in your case? (with `C:\Xenko\')

**Comment by boriscallens** [comment]
Breaking news: http://news.softpedia.com/news/microsoft-removes-260-characters-path-length-limit-in-windows-10-redstone-504596.shtml

**Comment by xen2** [comment]
Can you try again in 1.6.7? Hopefully it should be fixed!
(and reopen if it still happen)

**Comment by artganify** [comment]
Just tried with 1.6.8. Doesn't happen anymore. It's just 1.6.5 and 1.6.6. Weird.

**Comment by xen2** [comment]
Not weird, we fixed it in 1.6.7!
