### ISSUE TITLE
1.6.8 nvidia driver crash on startup

### ISSUE THREAD

**Issue by LennyPenny** [SiliconStudio/xenko#412]
Since I updated to version 1.6.8 every I time I start the editor my drivers crash making the editor have an unusable amount of lag. 

A few seconds after I get this error message
![http://i.imgur.com/4rTCkRe.png](http://i.imgur.com/4rTCkRe.png)

And here's the crash log from the report window
```
Application: GameStudio
UserEmail: 
UserMessage: 
XenkoVersion: 1.6.8-beta
GameStudioVersion: 4
ThreadName: EditorGameThread (prefabs/jet)
DefaultGraphicProfile: Level_11_0
LastActions: 
TransactionInProgress: 
CurrentDirectory: C:\Program Files\Silicon Studio\Xenko
CommandArgs: 
OsVersion: Microsoft Windows 10 Pro 10.0.10586 x64
ProcessorCount: 8
Exception: GraphicsException: Unexpected error on Present
   at SiliconStudio.Xenko.Graphics.SwapChainGraphicsPresenter.Present() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Graphics\Direct3D\SwapChainGraphicsPresenter.Direct3D.cs:line 162
   at SiliconStudio.Xenko.Games.GraphicsDeviceManager.SiliconStudio.Xenko.Games.IGraphicsDeviceManager.EndDraw(Boolean present) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GraphicsDeviceManager.cs:line 533
   at SiliconStudio.Xenko.Games.GameBase.EndDraw(Boolean present) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 823
   at SiliconStudio.Xenko.Engine.Game.EndDraw(Boolean present) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\Game.cs:line 368
   at SiliconStudio.Xenko.Games.GameBase.TickInternal() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 673
   at SiliconStudio.Xenko.Games.GameBase.Tick() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 502
   at SiliconStudio.Xenko.Games.GamePlatform.Tick() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GamePlatform.cs:line 177
   at SiliconStudio.Xenko.Games.GamePlatform.OnRunCallback() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GamePlatform.cs:line 149
   at SiliconStudio.Xenko.Games.WindowsMessageLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\Desktop\WindowsMessageLoop.cs:line 231
   at SiliconStudio.Xenko.Games.GameWindowWinforms.Run() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\Desktop\GameWindow.Windows.Desktop.cs:line 210
   at SiliconStudio.Xenko.Games.GameBase.Run(GameContext gameContext) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 463
   at SiliconStudio.Xenko.Assets.Presentation.AssetEditors.GameEditor.Services.EditorGameController.SceneGameRunThread() in C:\TeamCity\work\e71632f3cedbf5cf\sources\editor\SiliconStudio.Xenko.Assets.Presentation\AssetEditors\GameEditor\Services\EditorGameController.cs:line 205
   at SiliconStudio.Core.Diagnostics.SafeAction.<>c__DisplayClass1_0.<Wrap>b__0() in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core\Diagnostics\SafeAction.cs:line 30
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

InnerException:
  SharpDXException: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

     at SharpDX.Result.CheckError()
     at SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags)
     at SiliconStudio.Xenko.Graphics.SwapChainGraphicsPresenter.Present() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Graphics\Direct3D\SwapChainGraphicsPresenter.Direct3D.cs:line 153

GPU0.AdapterCompatibility: NVIDIA
GPU0.AdapterDACType: Integrated RAMDAC
GPU0.AdapterRAM: 2147483648
GPU0.Availability: 3
GPU0.Caption: NVIDIA GeForce GTX 670
GPU0.ConfigManagerErrorCode: 0
GPU0.ConfigManagerUserConfig: False
GPU0.CreationClassName: Win32_VideoController
GPU0.CurrentBitsPerPixel: 32
GPU0.CurrentHorizontalResolution: 1920
GPU0.CurrentNumberOfColors: 4294967296
GPU0.CurrentNumberOfColumns: 0
GPU0.CurrentNumberOfRows: 0
GPU0.CurrentRefreshRate: 60
GPU0.CurrentScanMode: 4
GPU0.CurrentVerticalResolution: 1080
GPU0.Description: NVIDIA GeForce GTX 670
GPU0.DeviceID: VideoController1
GPU0.DitherType: 0
GPU0.DriverDate: 20160307000000.000000-000
GPU0.DriverVersion: 10.18.13.6451
GPU0.InfFilename: oem29.inf
GPU0.InfSection: Section009
GPU0.InstalledDisplayDrivers: nvd3dumx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvd3dum,nvwgf2um,nvwgf2um,nvwgf2um
GPU0.MaxRefreshRate: 75
GPU0.MinRefreshRate: 50
GPU0.Monochrome: False
GPU0.Name: NVIDIA GeForce GTX 670
GPU0.PNPDeviceID: PCI\VEN_10DE&DEV_1189&SUBSYS_841A1043&REV_A1\4&F2959FF&0&0018
GPU0.Status: OK
GPU0.SystemCreationClassName: Win32_ComputerSystem
GPU0.SystemName: LENNY-LENNY-PC
GPU0.VideoArchitecture: 5
GPU0.VideoMemoryType: 2
GPU0.VideoModeDescription: 1920 x 1080 x 4294967296 colors
GPU0.VideoProcessor: GeForce GTX 670
Log: 1: []: Error: BuildStep Build step list (4 items) failed.
2: []: Error: BuildStep Build step list (1 items) failed.
3: [ContentManager]: Error: The asset 'gey/grass' could not be found. Asset path should be 'MyFolder/MyAssetName'. Check that the path is correct and that the asset has been included into the build.
4: [SceneGame]: Error: Unexpected exception. SiliconStudio.Xenko.Graphics.GraphicsException: Unexpected error on Present ---> SharpDX.SharpDXException: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags)
   at SiliconStudio.Xenko.Graphics.SwapChainGraphicsPresenter.Present() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Graphics\Direct3D\SwapChainGraphicsPresenter.Direct3D.cs:line 153
   --- End of inner exception stack trace ---
   at SiliconStudio.Xenko.Graphics.SwapChainGraphicsPresenter.Present() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Graphics\Direct3D\SwapChainGraphicsPresenter.Direct3D.cs:line 162
   at SiliconStudio.Xenko.Games.GraphicsDeviceManager.SiliconStudio.Xenko.Games.IGraphicsDeviceManager.EndDraw(Boolean present) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GraphicsDeviceManager.cs:line 533
   at SiliconStudio.Xenko.Games.GameBase.EndDraw(Boolean present) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 823
   at SiliconStudio.Xenko.Engine.Game.EndDraw(Boolean present) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\Game.cs:line 368
   at SiliconStudio.Xenko.Games.GameBase.TickInternal() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 663
5: [SafeAction]: Fatal: Unexpected exception. SiliconStudio.Xenko.Graphics.GraphicsException: Unexpected error on Present ---> SharpDX.SharpDXException: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags)
   at SiliconStudio.Xenko.Graphics.SwapChainGraphicsPresenter.Present() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Graphics\Direct3D\SwapChainGraphicsPresenter.Direct3D.cs:line 153
   --- End of inner exception stack trace ---
   at SiliconStudio.Xenko.Graphics.SwapChainGraphicsPresenter.Present() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Graphics\Direct3D\SwapChainGraphicsPresenter.Direct3D.cs:line 162
   at SiliconStudio.Xenko.Games.GraphicsDeviceManager.SiliconStudio.Xenko.Games.IGraphicsDeviceManager.EndDraw(Boolean present) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GraphicsDeviceManager.cs:line 533
   at SiliconStudio.Xenko.Games.GameBase.EndDraw(Boolean present) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 823
   at SiliconStudio.Xenko.Engine.Game.EndDraw(Boolean present) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\Game.cs:line 368
   at SiliconStudio.Xenko.Games.GameBase.TickInternal() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 673
   at SiliconStudio.Xenko.Games.GameBase.Tick() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 502
   at SiliconStudio.Xenko.Games.GamePlatform.Tick() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GamePlatform.cs:line 177
   at SiliconStudio.Xenko.Games.GamePlatform.OnRunCallback() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GamePlatform.cs:line 149
   at SiliconStudio.Xenko.Games.WindowsMessageLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\Desktop\WindowsMessageLoop.cs:line 231
   at SiliconStudio.Xenko.Games.GameWindowWinforms.Run() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\Desktop\GameWindow.Windows.Desktop.cs:line 210
   at SiliconStudio.Xenko.Games.GameBase.Run(GameContext gameContext) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 463
   at SiliconStudio.Xenko.Assets.Presentation.AssetEditors.GameEditor.Services.EditorGameController.SceneGameRunThread() in C:\TeamCity\work\e71632f3cedbf5cf\sources\editor\SiliconStudio.Xenko.Assets.Presentation\AssetEditors\GameEditor\Services\EditorGameController.cs:line 205
   at SiliconStudio.Core.Diagnostics.SafeAction.<>c__DisplayClass1_0.<Wrap>b__0() in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core\Diagnostics\SafeAction.cs:line 19


```

**Comment by LennyPenny** [comment]
updating my video drivers fixed the issue
