### ISSUE TITLE
Exception when closing Constraints sample

### ISSUE THREAD

**Issue by trombica** [SiliconStudio/xenko#413]
Just compile and run unmodified sample from Visual Studio and when closing the game window clicking x I get the exception: "Collection was modified; enumeration operation may not execute." in the ConstraintsApp.cs with the following specification:

{System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at SiliconStudio.Xenko.Physics.RigidbodyComponent.OnDetach() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Physics\Elements\RigidbodyComponent.cs:line 347
   at SiliconStudio.Xenko.Engine.PhysicsComponent.Detach() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Physics\Engine\PhysicsComponent.cs:line 668
   at SiliconStudio.Xenko.Physics.PhysicsProcessor.OnEntityComponentRemoved(Entity entity, PhysicsComponent component, AssociatedData data) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Physics\Engine\PhysicsProcessor.cs:line 147
   at SiliconStudio.Xenko.Engine.EntityProcessor`2.ProcessEntityComponent(Entity entity, EntityComponent entityComponentArg, Boolean forceRemove) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\EntityProcessor.cs:line 288
   at SiliconStudio.Xenko.Engine.EntityManager.CheckEntityComponentWithProcessors(Entity entity, EntityComponent component, Boolean forceRemove, List`1 dependentProcessors) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\EntityManager.cs:line 507
   at SiliconStudio.Xenko.Engine.EntityManager.CheckEntityWithProcessors(Entity entity, Boolean forceRemove, Boolean collecComponentTypesAndProcessors) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\EntityManager.cs:line 479
   at SiliconStudio.Xenko.Engine.EntityManager.InternalRemoveEntity(Entity entity, Boolean removeParent) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\EntityManager.cs:line 279
   at SiliconStudio.Xenko.Engine.EntityManager.Reset() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\EntityManager.cs:line 168
   at SiliconStudio.Xenko.Engine.SceneInstance.Reset() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\SceneInstance.cs:line 248
   at SiliconStudio.Xenko.Engine.SceneInstance.Destroy() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\SceneInstance.cs:line 107
   at SiliconStudio.Core.DisposeBase.SiliconStudio.Core.IReferencable.Release() in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core\DisposeBase.cs:line 59
   at SiliconStudio.Xenko.Engine.SceneSystem.Destroy() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\SceneSystem.cs:line 91
   at SiliconStudio.Core.DisposeBase.SiliconStudio.Core.IReferencable.Release() in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core\DisposeBase.cs:line 59
   at SiliconStudio.Core.DisposeBase.Dispose() in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core\DisposeBase.cs:line 20
   at SiliconStudio.Xenko.Games.GameBase.Destroy() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Games\GameBase.cs:line 756
   at SiliconStudio.Xenko.Engine.Game.Destroy() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\Game.cs:line 207
   at SiliconStudio.Core.DisposeBase.SiliconStudio.Core.IReferencable.Release() in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core\DisposeBase.cs:line 59
   at SiliconStudio.Core.DisposeBase.Dispose() in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core\DisposeBase.cs:line 20
   at Constraints.ConstraintsApp.Main(String[] args) in C:\Users\Malnar\Documents\Paradox Projects\Constraints\Constraints\Constraints.Windows\ConstraintsApp.cs:line 12
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()}

**Comment by sinkingsugar** [comment]
Thanks for the report!, will be fixed in the next release!

**Comment by sinkingsugar** [comment]
Once a new release comes out, to fix it you would need to regenerate the sample or remove the Cancel method from the DemoScript

**Comment by trombica** [comment]
Thans for a very fast reaction :+1:
