### ISSUE TITLE
[GameStudio] Crash while changing layout type

### ISSUE THREAD

**Issue by Maxdg95** [SiliconStudio/xenko#547]
> LastActions: * -[Paste into selection]
    * {OverrideValueChangeOperation: Parts ++[] = UIElementDesign [ToggleButton, ]}
    * {OverrideValueChangeOperation: Parts ++[] = UIElementDesign [TextBlock, ]}
    * {OverrideValueChangeOperation: Children ++[10] = SiliconStudio.Xenko.UI.Controls.ToggleButton}
    * {FixAssetCompositeHierarchyReferenceOperation`2}
> * -[Paste into selection]
    * {OverrideValueChangeOperation: Parts ++[] = UIElementDesign [ToggleButton, ]}
    * {OverrideValueChangeOperation: Parts ++[] = UIElementDesign [TextBlock, ]}
    * {OverrideValueChangeOperation: Children ++[11] = SiliconStudio.Xenko.UI.Controls.ToggleButton}
    * {FixAssetCompositeHierarchyReferenceOperation`2}
> * -[Paste into selection]
    * {OverrideValueChangeOperation: Parts ++[] = UIElementDesign [ToggleButton, ]}
    * {OverrideValueChangeOperation: Parts ++[] = UIElementDesign [TextBlock, ]}
    * {OverrideValueChangeOperation: Children ++[12] = SiliconStudio.Xenko.UI.Controls.ToggleButton}
    * {FixAssetCompositeHierarchyReferenceOperation`2}
> * -[Paste into selection]
    * {OverrideValueChangeOperation: Parts ++[] = UIElementDesign [ToggleButton, ]}
    * {OverrideValueChangeOperation: Parts ++[] = UIElementDesign [TextBlock, ]}
    * {OverrideValueChangeOperation: Children ++[13] = SiliconStudio.Xenko.UI.Controls.ToggleButton}
    * {FixAssetCompositeHierarchyReferenceOperation`2}
> * -[Paste into selection]
    * {OverrideValueChangeOperation: Parts ++[] = UIElementDesign [ToggleButton, ]}
    * {OverrideValueChangeOperation: Parts ++[] = UIElementDesign [TextBlock, ]}
    * {OverrideValueChangeOperation: Children ++[14] = SiliconStudio.Xenko.UI.Controls.ToggleButton}
    * {FixAssetCompositeHierarchyReferenceOperation`2}

> CurrentDirectory: C:\Program Files\Silicon Studio\Xenko
CommandArgs: /LauncherWindowHandle 1049298 C:\Users\GS\Documents\XE_KENO_SW\Keno\Keno.sln
OsVersion: Microsoft Windows 10 Pro 10.0.14393 x64
ProcessorCount: 8
Exception: NullReferenceException: Object reference not set to an instance of an object.
   at SiliconStudio.Xenko.UI.Panels.Canvas.InvalidateCanvasMeasure[T](Object propertyOwner, PropertyKey`1 propertyKey, T propertyOldValue) in C:\TeamCity\work\80a49494ba341a6a\sources\engine\SiliconStudio.Xenko.UI\Panels\Canvas.cs:line 72
   at SiliconStudio.Core.ObjectInvalidationMetadata`1.Invalidate(Object propertyOwner, PropertyKey propertyKey, Object propertyOldValue) in C:\TeamCity\work\80a49494ba341a6a\sources\common\core\SiliconStudio.Core\ObjectInvalidationMetadata.cs:line 75
   at SiliconStudio.Core.PropertyContainer.SetObject(PropertyKey propertyKey, Object tagValue, Boolean tryToAdd) in C:\TeamCity\work\80a49494ba341a6a\sources\common\core\SiliconStudio.Core\PropertyContainer.cs:line 537
   at SiliconStudio.Core.PropertyContainerClass.System.Collections.Generic.IDictionary<SiliconStudio.Core.PropertyKey,System.Object>.Add(PropertyKey key, Object value) in C:\TeamCity\work\80a49494ba341a6a\sources\common\core\SiliconStudio.Core\PropertyContainerClass.cs:line 174
   at SiliconStudio.Core.Serialization.Serializers.DictionaryAllSerializer`3.Serialize(TDictionary& obj, ArchiveMode mode, SerializationStream stream) in C:\TeamCity\work\80a49494ba341a6a\sources\common\core\SiliconStudio.Core\Serialization\Serializers\CollectionSerializers.cs:line 496
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream) in C:\TeamCity\work\80a49494ba341a6a\sources\common\core\SiliconStudio.Core\Serialization\DataSerializer.cs:line 85
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.SerializeExtended(T& obj, ArchiveMode mode, SerializationStream stream, DataSerializer`1 dataSerializer) in C:\TeamCity\work\80a49494ba341a6a\sources\common\core\SiliconStudio.Core\Serialization\MemberSerializerGenerated.cs:line 1425
   at SiliconStudio.Assets.AssetCloner.Clone() in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\AssetCloner.cs:line 112
   at SiliconStudio.Xenko.Assets.Presentation.AssetEditors.UIEditor.ViewModels.PanelViewModel.CopyCommonProperties(INodeContainer nodeContainer, Panel sourcePanel, Panel targetPanel) in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Xenko.Assets.Presentation\AssetEditors\UIEditor\ViewModels\PanelViewModel.cs:line 634
   at SiliconStudio.Xenko.Assets.Presentation.AssetEditors.UIEditor.ViewModels.PanelViewModel.CopySwapExchange(PanelViewModel sourcePanel, UIElementDesign targetPanel, Func`2 childSorter) in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Xenko.Assets.Presentation\AssetEditors\UIEditor\ViewModels\PanelViewModel.cs:line 531
   at SiliconStudio.Xenko.Assets.Presentation.AssetEditors.UIEditor.ViewModels.PanelViewModel.ChangeLayoutType(IUIElementFactory factory) in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Xenko.Assets.Presentation\AssetEditors\UIEditor\ViewModels\PanelViewModel.cs:line 299
   at SiliconStudio.Presentation.Commands.AnonymousCommand`1.Execute(Object parameter) in C:\TeamCity\work\80a49494ba341a6a\sources\common\presentation\SiliconStudio.Presentation\Commands\AnonymousCommand.cs:line 125
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at SiliconStudio.Xenko.GameStudio.Program.Main()

When I attempt to switch StackPanel to Grid, also happens when attempting to change Root Grid to different layout type.

**Comment by Kryptos-FR** [comment]
Thanks for the report. This has been fixed internally already.

**Comment by Maxdg95** [comment]
Also fixed, well done on the fixes Xenko!
